---
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Add Elasticsearch OpenSource repo
      yum_repository:
        name: Elasticsearch-OS
        baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
        description: ELK OpenSource repo
        gpgcheck: false

    - name: Install ELK stack & Heartbeat
      yum:
        name: "{{ item }}"
      loop:
        - heartbeat-elastic-7.8.0-1
        - elasticsearch-oss-7.8.0-1
        - logstash-oss-7.8.0-1
        - kibana-oss-7.8.0-1

    - name: Start ELK services & Heartbeat
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - heartbeat-elastic
        - elasticsearch
        - kibana
        - logstash

    - name: Copy file with Elasticsearch config
      copy:
        src: files/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0660'
      notify: restart_elasticsearch

    - name: Copy file with Kibana config
      copy:
        src: files/kibana.yml
        dest: /etc/kibana/kibana.yml
        owner: root
        group: kibana
        mode: '0660'
      notify: restart_kibana

    - name: Copy file with Heartbeat config
      copy:
        src: files/heartbeat.yml
        dest: /etc/heartbeat/heartbeat.yml
        owner: root
        group: root
        mode: '0600'
      notify: restart_heartbeat

    - name: Copy file with Logstash config
      copy:
        src: files/logstash.yml
        dest: /etc/logstash/logstash.yml
        owner: root
        group: logstash
        mode: '0660'
      notify: restart_logstash

    - name: Copy file with Logstash's pipeline config
      copy:
        src: files/pipeline.conf
        dest: /etc/logstash/conf.d/pipeline.conf
        owner: root
        group: logstash
        mode: '0660'
      notify: restart_logstash

    - name: Install Logtrail as plugin for Kibana
      command:
        cmd: >
          ./kibana-plugin --allow-root install \
          https://github.com/sivasamyk/logtrail/releases/download/v0.1.31/logtrail-7.8.0-0.1.31.zip
        chdir: /usr/share/kibana/bin
        # creates: /usr/share/kibana/plugins/logtrail/

    - name: Copy file with Logtrail config
      copy:
        src: files/logtrail.json
        dest: /usr/share/kibana/plugins/logtrail/logtrail.json
        owner: root
        group: root
        mode: '0664'
      notify: restart_kibana

  handlers:
    - name: Restart Elasticsearch
      service:
        name: elasticsearch
        state: restarted
      listen: restart_elasticsearch

    - name: Restart Kibana
      service:
        name: kibana
        state: restarted
      listen: restart_kibana

    - name: Restart Heartbeat
      service:
        name: heartbeat-elastic
        state: restarted
      listen: restart_heartbeat

    - name: Restart Logstash
      service:
        name: logstash
        state: restarted
      listen: restart_logstash
