---
- hosts: localhost
  connection: local
  gather_facts: false
  become: true
  tasks:
    - name: Add Elasticsearch OpenSource repo
      yum_repository:
        name: Elasticsearch-OS
        baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
        description: ELK OpenSource repo
        gpgcheck: false

    - name: Install ELK stack & Heartbeat
      yum:
        name: "{{ item }}"
      loop:
        - heartbeat-elastic
        - elasticsearch-oss
        - logstash-oss
        - kibana-oss

    - name: Start ELK services & Heartbeat
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - heartbeat-elastic
        - elasticsearch
        - kibana

    - name: Copy file with Elasticsearch config
      copy:
        src: files/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0660'
      notify: restart_elasticsearch

    - name: Copy file with Kibana config
      copy:
        src: files/kibana.yml
        dest: /etc/kibana/kibana.yml
        owner: root
        group: kibana
        mode: '0660'
      notify: restart_kibana

    - name: Copy file with Heartbeat config
      copy:
        src: files/heartbeat.yml
        dest: /etc/heartbeat/heartbeat.yml
        owner: root
        group: root
        mode: '0600'
      notify: restart_heartbeat

    # more tasks will go here!!!

  handlers:
    - name: Restart Elasticsearch
      service:
        name: elasticsearch
        state: restarted
      listen: restart_elasticsearch

    - name: Restart Kibana
      service:
        name: kibana
        state: restarted
      listen: restart_kibana

    - name: Restart Heartbeat
      service:
        name: heartbeat-elastic
        state: restarted
      listen: restart_heartbeat
